name: Markdown to PDF automation

on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
  workflow_dispatch:      

jobs:
  md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Convert md to pdf
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: pdf
          build_html: false
          theme: esn.css
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: 'pdf'
          pull: NO-PULL
