name: Markdown to PDF automation

on:
  push:
    branches: [ master ]
    paths:
      - '**.md'

jobs:
  md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ${{ github.workspace }}
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: ${{ github.workspace }}
