name: Markdowwn to PDF with pandoc

on:
  push:
    branches: [ master ]
    paths:
      - '**.md'
  workflow_dispatch:   

jobs:
  md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build -t esndoc . < Dockerfile 
      
      - name: Build the pdf
        run: |
          MDFILELIST=$(ls ${{ github.workspace }}/*.md)
          for mdfile in "${MDFILELIST}"
          do
            docker run --rm -u `id -u`:`id -g` -v `pwd`:/pandoc esndoc ${mdfile} -o pdfs/${mdfile%.*}.pdf --pdf-engine=xelatex --template=esn.tex  
          done
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: 'pdf'
          pull: NO-PULL
